export const mockProducts = [
    {
        id: 1,
        name: "Floral Elegance Eau de Parfum",
        description: "A luxurious floral fragrance with notes of rose, jasmine, and vanilla. Long-lasting and elegant.",
        price: 89.99,
        rating: 4.8,
        reviewCount: 124,
        image: "/placeholder.svg?height=400&width=400",
        category: "Perfumes",
        isNew: true,
        isSale: false,
        brand: "Chanel",
    },
    {
        id: 2,
        name: "Vitamin C Brightening Serum",
        description:
            "Powerful 20% vitamin C serum that brightens skin, reduces dark spots, and boosts collagen production.",
        price: 59.99,
        originalPrice: 79.99,
        rating: 4.9,
        reviewCount: 86,
        image: "/mock-product/vitamin-c.jpg",
        category: "Skincare",
        isNew: false,
        isSale: true,
        brand: "The Ordinary",
    },
    {
        id: 3,
        name: "Matte Velvet Lipstick",
        description: "Long-wearing matte lipstick with a velvety finish. Highly pigmented and comfortable to wear.",
        price: 24.99,
        rating: 4.7,
        reviewCount: 52,
        image: "/placeholder.svg?height=400&width=400",
        category: "Makeup",
        isNew: true,
        isSale: false,
        brand: "MAC Cosmetics",
    },
    {
        id: 4,
        name: "Hydrating Face Moisturizer",
        description: "Rich yet lightweight moisturizer with hyaluronic acid and ceramides for 24-hour hydration.",
        price: 34.99,
        rating: 4.6,
        reviewCount: 38,
        image: "/placeholder.svg?height=400&width=400",
        category: "Skincare",
        isNew: false,
        isSale: false,
        brand: "CeraVe",
    },
    {
        id: 5,
        name: "Silk Protein Hair Mask",
        description: "Intensive repair treatment with silk proteins and argan oil for damaged and dry hair.",
        price: 49.99,
        originalPrice: 69.99,
        rating: 4.8,
        reviewCount: 75,
        image: "/mock-product/hair-musk.jpg",
        category: "Hair Care",
        isNew: false,
        isSale: true,
        brand: "Olaplex",
    },
    {
        id: 6,
        name: "Exfoliating Body Scrub",
        description: "Gentle yet effective body scrub with natural exfoliants to reveal smoother, softer skin.",
        price: 28.99,
        rating: 4.5,
        reviewCount: 42,
        image: "/placeholder.svg?height=400&width=400",
        category: "Body Care",
        isNew: true,
        isSale: false,
        brand: "Sol de Janeiro",
    },
    {
        id: 7,
        name: "Facial Cleansing Brush",
        description: "Sonic cleansing device that deeply cleanses pores and exfoliates for clearer skin.",
        price: 129.99,
        rating: 4.3,
        reviewCount: 28,
        image: "/placeholder.svg?height=400&width=400",
        category: "Beauty Tools",
        isNew: false,
        isSale: false,
        brand: "Foreo",
    },
    {
        id: 8,
        name: "Men's Cologne Gift Set",
        description: "Luxury cologne set with three different scents for any occasion. Perfect for gifting.",
        price: 79.99,
        rating: 4.9,
        reviewCount: 64,
        image: "/placeholder.svg?height=400&width=400",
        category: "Men's Grooming",
        isNew: false,
        isSale: false,
        brand: "Tom Ford",
    },
    {
        id: 9,
        name: "Women's Perfume Set",
        description: "Luxury perfume set with three different scents for any occasion. Perfect for gifting.",
        price: 79.99,
        rating: 4.9,
        reviewCount: 64,
        image: "/placeholder.svg?height=400&width=400",
        category: "Women's Grooming",
        isNew: false,
        isSale: false,
        brand: "Chanel",
    },
    {
        id: 10,
        name: "Men's Cologne Gift Set",
        description: "Luxury cologne set with three different scents for any occasion. Perfect for gifting.",
        price: 79.99,
        rating: 4.9,
        reviewCount: 64,
        image: "/placeholder.svg?height=400&width=400",
        category: "Men's Grooming",
        isNew: false,
        isSale: false,
        brand: "Chanel",
    },
    {
        id: 11,
        name: "Women's Perfume Set",
        description: "Luxury perfume set with three different scents for any occasion. Perfect for gifting.",
        price: 79.99,
        rating: 4.9,
        reviewCount: 64,
        image: "/placeholder.svg?height=400&width=400",
        category: "Women's Grooming",
        isNew: false,
        isSale: false,
        brand: "Chanel",
    },
    {
        id: 12,
        name: "Men's Cologne Gift Set",
        description: "Luxury cologne set with three different scents for any occasion. Perfect for gifting.",
        price: 79.99,
        rating: 4.9,
        reviewCount: 64,
        image: "/placeholder.svg?height=400&width=400",
        category: "Men's Grooming",
        isNew: false,
        isSale: false,
        brand: "Chanel",
    },
    {
        id: 13,
        name: "Amber Oud Eau de Parfum",
        description: "A deep, woody fragrance with rich amber, oud, and spice notes. Luxurious and long-lasting.",
        price: 99.99,
        rating: 4.8,
        reviewCount: 132,
        image: "/placeholder.svg?height=400&width=400",
        category: "Perfumes",
        isNew: true,
        isSale: false,
        brand: "Armani",
    },
    {
        id: 14,
        name: "Niacinamide 10% + Zinc 1% Serum",
        description: "A lightweight serum that reduces redness, controls oil, and refines skin texture.",
        price: 12.99,
        rating: 4.7,
        reviewCount: 189,
        image: "/mock-product/vitamin-c.jpg",
        category: "Skincare",
        isNew: false,
        isSale: true,
        brand: "The Ordinary",
    },
    {
        id: 15,
        name: "Long-Lasting Liquid Foundation",
        description: "Oil-free, full-coverage foundation with a natural matte finish. Stays flawless for 24 hours.",
        price: 42.99,
        rating: 4.8,
        reviewCount: 210,
        image: "/placeholder.svg?height=400&width=400",
        category: "Makeup",
        isNew: true,
        isSale: false,
        brand: "Fenty Beauty",
    },
    {
        id: 16,
        name: "Repair & Strengthen Hair Oil",
        description: "Lightweight yet nourishing hair oil that tames frizz and strengthens damaged hair.",
        price: 29.99,
        rating: 4.6,
        reviewCount: 95,
        image: "/placeholder.svg?height=400&width=400",
        category: "Hair Care",
        isNew: false,
        isSale: false,
        brand: "Moroccanoil",
    },
    {
        id: 17,
        name: "Shea Butter Hand Cream",
        description: "Ultra-rich hand cream with 20% shea butter to deeply nourish and protect dry hands.",
        price: 15.99,
        rating: 4.9,
        reviewCount: 84,
        image: "/mock-product/hair-musk.jpg",
        category: "Body Care",
        isNew: false,
        isSale: true,
        brand: "L'Occitane",
    },
    {
        id: 18,
        name: "Detox Charcoal Face Mask",
        description: "Purifying mask with activated charcoal to draw out impurities and minimize pores.",
        price: 19.99,
        rating: 4.7,
        reviewCount: 145,
        image: "/placeholder.svg?height=400&width=400",
        category: "Skincare",
        isNew: true,
        isSale: false,
        brand: "Origins",
    },
    {
        id: 19,
        name: "Luxury Beard Grooming Kit",
        description: "Complete grooming set with beard oil, balm, and a wooden comb for ultimate beard care.",
        price: 54.99,
        rating: 4.8,
        reviewCount: 76,
        image: "/placeholder.svg?height=400&width=400",
        category: "Men's Grooming",
        isNew: false,
        isSale: false,
        brand: "Beardbrand",
    },
    {
        id: 20,
        name: "LED Light Therapy Face Mask",
        description: "At-home LED therapy mask that targets acne, wrinkles, and uneven skin tone.",
        price: 159.99,
        rating: 4.5,
        reviewCount: 54,
        image: "/placeholder.svg?height=400&width=400",
        category: "Beauty Tools",
        isNew: false,
        isSale: false,
        brand: "Dr. Dennis Gross",
    }
]