export const mockFeaturedBrands = [
    {
        id: 1,
        name: "Chanel",
        description:
            "Luxury French fashion house specializing in high-end fragrances and cosmetics",
        image: "/brand/chanel.jpg",
        rating: 4.9,
        reviewCount: 245,
        productCount: 78,
        featured: true,
    },
    {
        id: 2,
        name: "The Ordinary",
        description: "Clinical formulations with integrity, focused on effective skincare solutions",
        image: "/brand/ordinary.jpg",
        rating: 4.8,
        reviewCount: 187,
        productCount: 56,
        featured: true,
    },
    {
        id: 3,
        name: "MAC Cosmetics",
        description: "Professional quality makeup for all ages, races, and genders",
        image: "/brand/mac.jpg",
        rating: 4.7,
        reviewCount: 163,
        productCount: 42,
        featured: true,
    },
    {
        id: 4,
        name: "Olaplex",
        description: "Revolutionary hair care system that repairs and strengthens damaged hair",
        image: "/brand/ola.jpg",
        rating: 4.6,
        reviewCount: 128,
        productCount: 35,
        featured: true,
    },
]